version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
        - "discovery.type=single-node"
        - "DISABLE_INSTALL_DEMO_CONFIG=true"
        - bootstrap.memory_lock=true
        - OPENSEARCH_USERNAME="admin"
        - OPENSEARCH_PASSWORD="password"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.3
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    ports:
      - 2055:2055/udp
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
      - 5560:5560/udp
      - 1514:1514/udp
    volumes:
      #- ./logstash/logstash.yml:/usr/share/logstash/logstash.yml:ro
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - opensearch-net

volumes:
  opensearch:

networks:
  opensearch-net:
