- name: Configure Monitoring VM
  hosts: monitoring
  tasks:
  - name: Update all packages
    ansible.builtin.apt:
      name: "*"
      state: latest
    become: true

  - name: Install required system packages
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - gnupg2
      update_cache: true
    become: true

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    become: true

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    become: true

  - name: Update apt and install docker-ce
    ansible.builtin.apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
      update_cache: true
    become: true

  - name: Install Microsoft Powershell
    ansible.builtin.apt:
      deb: https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-lts_7.2.6-1.deb_amd64.deb
    become: true

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0777'
    loop:
      - /var/requirements
    become: true

  - name: Copy Docker configurations
    ansible.builtin.copy:
      src: "./docker"
      dest: /var/requirements
      mode: '0777'
      force: true
    become: true
    register: copy_requirements
    tags: "copy"

  - name: Deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /var/requirements/docker
      files:
        - docker-compose.yaml
    become: true



